[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "txai_omics_3"
version = "0.1.1"
description = "A library with several BioAge prediction models."
readme = "README.md"
authors = [
  "Igor Yusipov <yusipov.igor@itmm.unn.ru>"
]
maintainers = [
    "Igor Yusipov <yusipov.igor@itmm.unn.ru>"
]
repository = "https://github.com/GillianGrayson/txai_omics_3"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
matplotlib = "3.7.3"
black = "21.12b0"
python-dotenv = "1.0.1"
hydra-core = "1.2.0"
hydra-colorlog = "1.2.0"
hydra-optuna-sweeper = "1.2.0"
pyrootutils = "1.0.4"
scipy = "1.12.0"
numpy = "1.26.4"
pytorch-tabular = "1.1.0"
pytorch-widedeep = "1.1.1"
xgboost = "2.1.0"
catboost = "1.2.5"
lightgbm = "3.3.0"
python-slugify = "8.0.4"
seaborn = "0.12.2"
distinctipy = "1.3.4"
jupyter = "1.0.0"
plotly = "5.22.0"
patchworklib = "0.6.4"
shap = "0.46.0"
lime = "0.2.0.1"
adversarial-robustness-toolbox = "1.18.1"
pyod = "2.0.1"
pythresh = "0.3.6"
combo = "0.1.3"
geomstats = "2.7.0"
pyclustering = "0.10.1.2"
ruptures = "1.1.9"
scikit-lego = "0.9.1"
opentsne = "1.0.1"
sdv = "1.15.0"
wandb = "0.17.4"
openpyxl = "3.1.5"

[tool.poetry.group.dev.dependencies]
pytest = "*"
